# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

registries:
  # @see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot
  # the credentials for the private registries are configured in the uniport organization: https://github.com/organizations/uniport/settings/secrets/private_registries
  inventage-maven:
    type: maven-repository
    url: https://nexus3.inventage.com/repository/inventage-portal-maven-group
    replaces-base: true
  inventage-npm:
    type: npm-registry
    url: https://nexus3.inventage.com/repository/inventage-portal-npm-group
    replaces-base: true

updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - inventage-maven
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "io.micrometer:micrometer-registry-prometheus" # required to be in sync with vertx-micrometer-metrics
    open-pull-requests-limit: 10
    labels:
      - "java"
      - "dependencies"
      - "no changelog"

  - package-ecosystem: "npm"
    directory: "/docs/src/main/mkdocs"
    registries:
      - inventage-npm
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "javascript"
      - "dependencies"
      - "no changelog"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "no changelog"
