name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
type: Bug
assignees:
  - fbuetler
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version(s) did you encounter this bug ?
      placeholder: ex. 9.5.0-202506100904-135-d216a4a
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
        4. ...
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here like OS/JVM/Browser version.
    validations:
      required: false
  - type: input
    id: reproducer
    attributes:
      label: Do you have a reproducer?
      description: |
        A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that
        has a build file that can be executed to reproduce the issue.

        Reproducers are very helpful for contributors and will likely help them fixing your bug faster.
      placeholder: Link to github project/gist
    validations:
      required: false
