name: Feature request
description: Suggest a feature for this project
labels: ["enhancement"]
type: Feature
assignees:
  - fbuetler
body:
  - type: markdown
    attributes:
      value: |
        Read this first before creating an issue:

        - do not use this issue tracker to ask questions, instead start a [discussion](https://github.com/uniport/portal-gateway/discussions). Questions will likely be closed without notice.
        - you shall create a feature request only when it is general purpose enough.
        - make sure that the feature is not already implemented.
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here like OS/JVM/Browser version.
    validations:
      required: false
  - type: input
    id: contribution
    attributes:
      label: Contribution
      description: |
        Who should implement this feature ? are you volunteering for implementing this feature or
        do you know that is able and willing implement this feature ?
    validations:
      required: false
