# @see https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
site_name: Uniport-Gateway
site_description: Uniport-Gateway Documentation
site_author: uniport.ch
dev_addr: "127.0.0.1:8000"

# Breaks docker usage of mkdocs :/
# @see https://github.com/squidfunk/mkdocs-material/issues/1691
# strict: true

# Repository
repo_name: uniport-gateway
repo_url: https://github.com/uniport/uniport-gateway

docs_dir: "content"

# @see https://squidfunk.github.io/mkdocs-material/setup/
theme:
  name: material
  logo: assets/img/uniport-symbol-white.svg
  favicon: assets/img/favicon-32x32.png
  font:
    text: DM Sans
    code: DM Mono
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - content.code.copy

# Styles
extra_css:
  - assets/css/extra.css

plugins:
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - toc:
      toc_depth: 5
      permalink: true
  # @see https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # Page tree


nav:
  - Uniport:
      - README.md
  - Introduction:
      - 01-introduction/index.md
  - Getting Started:
      - 02-getting-started/index.md
  - Configuration & Deployment:
      - 03-configuration-deployment/index.md
  - Customization:
      - 04-customization/index.md
  - Extending & Developing:
      - 05-extending-developing/index.md
  - API:
      - 06-api/index.md
  - Cheat Sheets:
      - 07-cheat-sheets/index.md
  - Troubleshooting:
      - 08-troubleshooting/index.md
