ingress:
  host: ips.inventage.dev
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/server-snippet: |
      location /.well-known/apple-app-site-association { 
        allow all; proxy_pass http://portal-gateway.ips:20000;
      }

      location /.well-known/assetlinks.json { 
          allow all; proxy_pass http://portal-gateway.ips:20000;
      }
  tls:
    enabled: true

services:
  portal-gateway:
    ports:
      http-debug:
        port: 20009

serviceMonitor:
  enabled: true

containers:
  portal-gateway:
    env:
      # HTTP protocol for external access
      PORTAL_GATEWAY_PUBLIC_PROTOCOL:
        value: "https"
        # HTTP host name for external access
      PORTAL_GATEWAY_PUBLIC_HOSTNAME:
        value: "ips.inventage.dev"
        # HTTP port for external access, must be the same as the exposed port
      PORTAL_GATEWAY_PUBLIC_PORT:
        value: "443"
      PORTAL_GATEWAY_BEARER_TOKEN_ISSUER:
        value: "https://ips.inventage.dev/auth/realms/portal"
      OTEL_TRACES_EXPORTER:
        value: "otlp"
      OTEL_EXPORTER_OTLP_ENDPOINT:
        value: "http://portal-monitoring-open-telemetry-collector.monitoring:4317"
      PORTAL_GATEWAY_STRUCTURAL_LOGGING_ENABLED:
        value: "true"
      PORTAL_GATEWAY_LOG_LEVEL:
        value: "DEBUG"
      PORTAL_GATEWAY_HEADLESS_SERVICE_NAME:
        value: "portal-gateway-headless.ips.svc.cluster.local"
      PORTAL_GATEWAY_ANALYTICS_HOST:
        value: analytics.analytics
      PORTAL_GATEWAY_PORTAL_GRAFANA_HOST:
        value: "grafana-grafana-service.monitoring.svc.cluster.local"
    storages:
      proxy-config:
        type: configMap
        configMapName: portal-gateway-proxy-config
        mountPath: /etc/uniport-gateway/default
        items:
          - key: uniport-gateway.json
            path: uniport-gateway.json
          - key: dynamic-config..analytics..config.json
            path: dynamic-config/analytics/config.json
          - key: dynamic-config..auth..config.json
            path: dynamic-config/auth/config.json
          - key: dynamic-config..base..config.json
            path: dynamic-config/base/config.json
          - key: dynamic-config..content..config.json
            path: dynamic-config/content/config.json
          - key: dynamic-config..conversation..config.json
            path: dynamic-config/conversation/config.json
          - key: dynamic-config..csp..config.json
            path: dynamic-config/csp/config.json
          - key: dynamic-config..dashboard..config.json
            path: dynamic-config/dashboard/config.json
          - key: dynamic-config..filestorage..config.json
            path: dynamic-config/filestorage/config.json
          - key: dynamic-config..general..config.json
            path: dynamic-config/general/config.json
          - key: dynamic-config..notification..config.json
            path: dynamic-config/notification/config.json
          - key: dynamic-config..organisation..config.json
            path: dynamic-config/organisation/config.json
          - key: dynamic-config..portal-database..config.json
            path: dynamic-config/portal-database/config.json
          - key: dynamic-config..portal-iam..config.json
            path: dynamic-config/portal-iam/config.json
          - key: dynamic-config..portal-messaging..config.json
            path: dynamic-config/portal-messaging/config.json
          - key: dynamic-config..portal-monitoring..config.json
            path: dynamic-config/portal-monitoring/config.json
        readOnly: true

configMaps:
  portal-gateway-proxy-config:
    enabled: true
    # The '..' character in the following key names DO NOT have a special meaning.
    # Its a limitation of k8s that configmap key have to consist of alphanumeric characters, -, _ or .
    # With the '..' characters we want to symbolize the path the config file will live under.
    data:
      uniport-gateway.json:
        valueFromFile: proxy-config.examples/uniport-gateway.json
      dynamic-config..analytics..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/analytics/config.json
      dynamic-config..auth..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/auth/config.json
      dynamic-config..base..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/base/config.json
      dynamic-config..content..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/content/config.json
      dynamic-config..conversation..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/conversation/config.json
      dynamic-config..csp..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/csp/config.json
      dynamic-config..dashboard..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/dashboard/config.json
      dynamic-config..filestorage..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/filestorage/config.json
      dynamic-config..general..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/general/config.json
      dynamic-config..notification..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/notification/config.json
      dynamic-config..organisation..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/organisation/config.json
      dynamic-config..portal-database..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/portal-database/config.json
      dynamic-config..portal-iam..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/portal-iam/config.json
      dynamic-config..portal-messaging..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/portal-messaging/config.json
      dynamic-config..portal-monitoring..config.json:
        valueFromFile: proxy-config.examples/dynamic-config/portal-monitoring/config.json
