containers:
  portal-gateway:
    image:
      tag: ${project.version}-native
    env:
      PORTAL_GATEWAY_LOGGING_CONFIG:
        value: "/etc/portal-gateway/logging-config/logback-structured-default.xml"
    storages:
      logging-config:
        type: configMap
        configMapName: portal-gateway-logging-config
        # As mounting a configMap creates a dir and mounts the config map's data as files in it
        # and there are existing files in /etc/portal-gateway, an additional path `logging-config` is used
        mountPath: /etc/portal-gateway/logging-config

configMaps:
  portal-gateway-logging-config:
    enabled: true
    data:
      # In our logback configuration we use a condition based on a env var to decide if we log structured or unstructured log messages.
      # For this we rely on a library called Janino.
      # See helm/src/main/resources/app-config/logback.xml.
      #
      # Unfortunately, Janino cannot be used with a native image build, hence we have two logback configurations for both cases.
      # To choose between the two configurations the PORTAL_GATEWAY_LOGGING_CONFIG env var can be used.
      # See: https://github.com/spring-projects/spring-boot/issues/33758
      logback-structured.xml:
        valueFromFile: app-config/logback-structured-default.xml
      logback-unstructured.xml:
        valueFromFile: app-config/logback-unstructured-default.xml
