global:
    imagePullSecrets:
        - name: inventage-portal-docker-group

ports:
    - name: http
      port: 20000

ingress:
    host: portal.10.100.20.40.nip.io
    port: 20000

envOverride:
  # HTTP protocol for external access
    - name: "PORTAL_GATEWAY_PUBLIC_PROTOCOL"
      value: "http"
  # HTTP host name for external access
    - name: "PORTAL_GATEWAY_PUBLIC_HOSTNAME"
      value: "portal.10.100.20.40.nip.io"
  # HTTP port for external access, must be the same as the exposed port
    - name: "PORTAL_GATEWAY_PUBLIC_PORT"
      value: "80"
  # IAM
    - name: "portal-iam.host"
      value: "portal-iam"
    - name: "portal-iam.port"
      value: "8080"
  # Navigation
    - name: "navigation-proxy.host"
      value: "navigation-proxy"
    - name: "navigation-proxy.port"
      value: "20010"
  # Dashboard
    - name: "dashboard-proxy.host"
      value: "dashboard-proxy"
    - name: "dashboard-proxy.port"
      value: "20020"
  # Organisation
    - name: "organisation-proxy.host"
      value: "organisation-proxy"
    - name: "organisation-proxy.port"
      value: "20030"
  # Document
    - name: "document-proxy.host"
      value: "document-proxy"
    - name: "document-proxy.port"
      value: "20050"
  # FileStorage
    - name: "filestorage-proxy.host"
      value: "filestorage-proxy"
    - name: "filestorage-proxy.port"
      value: "20090"
