replicaCount: 1

initContainers:
    - name: init-portal-iam
      image: busybox:1.33
      command:
          - "sh"
          - "-c"
          - "while ! nc -z portal-iam 8080; do true; done"
    - name: init-navigation-proxy
      image: busybox:1.33
      command:
          - "sh"
          - "-c"
          - "while ! nc -z navigation-proxy 20010; do true; done"
    - name: init-dashboard-proxy
      image: busybox:1.33
      command:
          - "sh"
          - "-c"
          - "while ! nc -z dashboard-proxy 20020; do true; done"
    - name: init-document-proxy
      image: busybox:1.33
      command:
          - "sh"
          - "-c"
          - "while ! nc -z document-proxy 20050; do true; done"
    - name: init-organisation-proxy
      image: busybox:1.33
      command:
          - "sh"
          - "-c"
          - "while ! nc -z organisation-proxy 20030; do true; done"

image:
    registry: ${docker.pull.registry}
    baseName: ${project.groupId}
    name: portal-gateway
    tag: ${project.version}
    pullPolicy: IfNotPresent

nameOverride: ""

podSecurityContext:
    enabled: false

containerSecurityContext:
    enabled: false

livenessProbe:
    enabled: true
    httpGet:
        path: /health
        port: http
    initialDelaySeconds: 10
    timeoutSeconds: 1
    periodSeconds: 20
    failureThreshold: 6
    successThreshold: 1

readinessProbe:
    enabled: true
    httpGet:
        path: /health
        port: http
    initialDelaySeconds: 10
    timeoutSeconds: 1
    periodSeconds: 20
    failureThreshold: 6
    successThreshold: 1

startupProbe:
    enabled: true
    httpGet:
        path: /health
        port: http
    initialDelaySeconds: 10
    timeoutSeconds: 1
    periodSeconds: 20
    failureThreshold: 6
    successThreshold: 1

service:
    type: ClusterIP

ports:
    - name: http
      port: 20000

ingress:
    enabled: true
    host: portal
    port: 20000
    className: ""
    annotations:
        {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"

resources: {}

storages: []

env:
    # HTTP protocol for external access
    - name: "PORTAL_GATEWAY_PUBLIC_PROTOCOL"
      value: "http"
    # HTTP host name for external access
    - name: "PORTAL_GATEWAY_PUBLIC_HOSTNAME"
      value: "${deploymentDomain}"
    # HTTP port for external access, must be the same as the exposed port
    - name: "PORTAL_GATEWAY_PUBLIC_PORT"
      value: "80"

    # IAM
    - name: "portal-iam.host"
      value: "portal-iam"
    - name: "portal-iam.port"
      value: "8080"
    # Navigation
    - name: "navigation-proxy.host"
      value: "navigation-proxy"
    - name: "navigation-proxy.port"
      value: "20010"
    # Dashboard
    - name: "dashboard-proxy.host"
      value: "dashboard-proxy"
    - name: "dashboard-proxy.port"
      value: "20020"
    # Organisation
    - name: "organisation-proxy.host"
      value: "organisation-proxy"
    - name: "organisation-proxy.port"
      value: "20030"
    # Document
    - name: "document-proxy.host"
      value: "document-proxy"
    - name: "document-proxy.port"
      value: "20050"
