version: '3'

services:
  portal-gateway:
    image: ${docker.pull.registry}/com.inventage.portal.gateway.portal-gateway:${project.version}
    networks:
      - portal-proxy
    ports:
      - "20000:20000" # docker-host.port:entrypoint.port
    env_file:
      - portal-gateway.common.env
      - portal-gateway.specific.env # deployments must create this file by copying a environment specific file
      - secrets.env

networks:
  portal-proxy:
    external:
      name: portal-proxy
