version: "2.4"

services:
    portal-gateway:
        image: ${docker.pull.registry}/${project.groupId}.portal-gateway:${project.version}
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - portal-gateway
        expose:
            - "20000"
        env_file:
            - portal-gateway.common.env
            - portal-gateway.specific.env # deployments must create this file by copying an environment specific file
            - secrets.env
        mem_limit: '256m'

networks:
    portal-gateway:
        external: true
