version: "3"

services:
  portal-gateway:
    image: ${docker.pull.registry}/com.inventage.portal.gateway.portal-gateway:${project.version}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portal-gateway
    ports:
      # docker-host.port:entrypoint.port, if not equals, docker-host.port must be same as PORTAL_GATEWAY_PUBLIC_PORT
      - "20000:20000"
    env_file:
      - portal-gateway.common.env
      - portal-gateway.specific.env # deployments must create this file by copying a environment specific file
      - secrets.env

networks:
  portal-gateway:
    external: true
