services:
  gateway:
    image: ghcr.io/uniport/uniport-gateway:10.0.0-202508211627-16-d140af6
    environment:
      - "UNIPORT_GATEWAY_JSON=/config/uniport-gateway.json"
      - "UNIPORT_GATEWAY_LOG_LEVEL=INFO"
      - "OTEL_TRACES_EXPORTER=none"
      - "OTEL_METRICS_EXPORTER=none"
    volumes:
      - ./step1:/config/
    ports:
      # API port
      - "20000:20000"
      - "20001:20001"
    networks:
      - uniport-gateway

  # example resource server
  whoami1:
    image: traefik/whoami
    expose:
      - "80"
    ports:
      - "8001:80"
    networks:
      - uniport-gateway

  # example resource server
  whoami2:
    image: traefik/whoami
    expose:
      - "80"
    ports:
      - "8002:80"
    networks:
      - uniport-gateway

networks:
  uniport-gateway:
    name: uniport-gateway-starter-kit
