services:
  gateway:
    image: uniportcr.artifacts.inventage.com/com.inventage.portal.gateway.portal-gateway:10.0.0-SNAPSHOT
    environment:
      - "PORTAL_GATEWAY_JSON=/config/portal-gateway.json"
      - "PORTAL_GATEWAY_LOG_LEVEL=INFO"
      - "OTEL_TRACES_EXPORTER=none"
      - "OTEL_METRICS_EXPORTER=none"
    volumes:
      - ./step1:/config/
    ports:
      # API port
      - "20000:20000"
      - "20001:20001"
    networks:
      - portal-gateway

  # example resource server
  whoami1:
    image: traefik/whoami
    expose:
      - "80"
    ports:
      - "8001:80"
    networks:
      - portal-gateway

  # example resource server
  whoami2:
    image: traefik/whoami
    expose:
      - "80"
    ports:
      - "8002:80"
    networks:
      - portal-gateway

networks:
  portal-gateway:
    name: portal-gateway-starter-kit
