name: 'Setup Java, Helm and Maven Access'
description: 'Sets up Java, Helm repositories and Maven access'
inputs:
  java-version:
    description: 'Java version'
    required: true
    default: '21'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup helm repositories
      shell: bash
      run: |
        helm repo add inventage-portal-helm https://nexus3.inventage.com/repository/inventage-portal-helm/ --username ${{ env.NEXUS_USER }} --password ${{ env.NEXUS_PW }}
        helm repo add inventage-portal-helm-staging https://nexus3.inventage.com/repository/inventage-portal-helm-staging/ --username ${{ env.NEXUS_USER }} --password ${{ env.NEXUS_PW }}

    - name: Login to docker registry
      uses: docker/login-action@v3
      with:
        registry: uniportcr.artifacts.inventage.com
        username: ${{ env.NEXUS_USER }}
        password: ${{ env.NEXUS_PW }}

    - name: Setup settings.xml
      uses: s4u/maven-settings-action@v3.1.0
      with:
        servers: |
          [
            {
              "id": "inventage-portal-group",
              "username": "${{ env.NEXUS_USER }}",
              "password": "${{ env.NEXUS_PW }}"
            }
          ]


