name: Deploy Preview
run-name: "Deployment #${{ github.run_number }}"

on:
  workflow_call:
    inputs:
      alias:
        description: "The netlify deployment alias"
        type: string
        default: ""
      artifact_name:
        description: "The name of the actions/upload-artifact artifact to deploy"
        required: true
        type: string
      artifact_path:
        description: "The path of the artifact in the actions/upload-artifact to deploy"
        type: string
        default: "build.zip"
      run_id:
        description: "The run-id of the workflow that uploaded the artifact"
        required: true
        type: string
      pr_number:
        description: "The PR number if a comment should be added"
        required: false
        default: -1
        type: number
      environment:
        description: "The GitHub environment name to deploy to"
        required: false
        default: "preview"
        type: string
    secrets:
      NETLIFY_AUTH_TOKEN:
        required: true
      NETLIFY_SITE_ID:
        required: true
  workflow_dispatch:
    inputs:
      alias:
        description: "The netlify deployment alias"
        type: string
        default: ""
      artifact_name:
        description: "The name of the actions/upload-artifact artifact to deploy"
        required: true
        type: string
      artifact_path:
        description: "The path of the artifact in the actions/upload-artifact to deploy"
        type: string
        default: "build.zip"
      run_id:
        description: "The run-id of the workflow that uploaded the artifact"
        required: true
        type: string
      pr_number:
        description: "The PR number if a comment should be added"
        required: false
        default: -1
        type: number
      environment:
        description: "The GitHub environment name to deploy to"
        required: false
        default: "preview"
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      actions: read # download artifacts
      statuses: write # create commit status
      pull-requests: write # update pull requests
      deployments: write # update deployment
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ inputs.run_id }}
          github-token: ${{ github.token }}
          name: ${{ inputs.artifact_name }}

      - name: Unzip artifact
        run: unzip ${{ inputs.artifact_path }}

      - name: Deploy to Netlify
        id: deployment
        uses: nwtgck/actions-netlify@v3.0
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          # netlify
          alias: ${{ inputs.alias }}
          publish-dir: "./build"
          deploy-message: "Deploy from GitHub Actions"
          production-branch: master
          fails-without-credentials: true
          # github
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-github-deployment: true
          github-deployment-environment: ${{ inputs.environment }}
          enable-commit-status: true
          enable-commit-comment: false
          enable-pull-request-comment: false # does not work
        timeout-minutes: 1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        if: ${{ inputs.pr_number > 0 }}
        with:
          pr-number: ${{ inputs.pr_number }}
          message: |
            Deployed a **preview** version to ${{ steps.deployment.outputs.deploy-url }}
          comment-tag: deployment

      - name: Summary
        if: always()
        run: |
          echo "## Deploy Details" >> $GITHUB_STEP_SUMMARY
          echo "This workflow ran on **$(date)**." >> $GITHUB_STEP_SUMMARY
          echo "### Inputs" >> $GITHUB_STEP_SUMMARY
          echo "- **alias**: \`${{ inputs.alias }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **artifact_name**: \`${{ inputs.artifact_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **artifact_path**: \`${{ inputs.artifact_path }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **run_id**: \`${{ inputs.run_id }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **deploy-url**: ${{ steps.deployment.outputs.deploy-url }}" >> $GITHUB_STEP_SUMMARY
