name: Deploy Preview
run-name: "Deployment #${{ github.run_number }}"

permissions:
  actions: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      alias:
        description: "The netlify deployment alias"
        type: string
        default: ""
      artifact_name:
        description: "The name of the actions/upload-artifact artifact to deploy"
        required: true
        type: string
      artifact_path:
        description: "The path of the artifact in the actions/upload-artifact to deploy"
        type: string
        default: "build.zip"
      run_id:
        description: "The run-id of the workflow that uploaded the artifact"
        required: true
        type: string
      pr_number:
        description: "The PR number if a comment should be added"
        required: false
        default: -1
        type: number
      environment:
        description: "The GitHub environment name to deploy to"
        required: false
        default: "preview"
        type: string
    outputs:
      DEPLOYMENT_URL:
        description: "The URL that was deployed to"
        value: ${{ jobs.setup.outputs.DEPLOYMENT_URL }}
    secrets:
      NETLIFY_AUTH_TOKEN:
        required: true
      NETLIFY_SITE_ID:
        required: true
  workflow_dispatch:
    inputs:
      alias:
        description: "The netlify deployment alias"
        type: string
        default: ""
      artifact_name:
        description: "The name of the actions/upload-artifact artifact to deploy"
        required: true
        type: string
      artifact_path:
        description: "The path of the artifact in the actions/upload-artifact to deploy"
        type: string
        default: "build.zip"
      run_id:
        description: "The run-id of the workflow that uploaded the artifact"
        required: true
        type: string
      pr_number:
        description: "The PR number if a comment should be added"
        required: false
        default: -1
        type: number
      environment:
        description: "The GitHub environment name to deploy to"
        required: false
        default: "preview"
        type: string

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      DEPLOYMENT_URL: ${{ steps.variables.outputs.DEPLOYMENT_URL }}
    steps:
      - name: Variables
        id: variables
        run: |
          echo "DEPLOYMENT_URL=https://${{ inputs.alias }}--${{ vars.NETLIFY_DEPLOYMENT_URL }}" >> $GITHUB_OUTPUT

          if [ "${{ inputs.alias }}" = "master" ]; then
            echo "DEPLOYMENT_URL=https://${{ vars.NETLIFY_DEPLOYMENT_URL }}" >> $GITHUB_OUTPUT
          else
            echo "DEPLOYMENT_URL=https://${{ inputs.alias }}--${{ vars.NETLIFY_DEPLOYMENT_URL }}" >> $GITHUB_OUTPUT
          fi
      - name: Summary
        if: always()
        run: |
          echo "## Setup Details" >> $GITHUB_STEP_SUMMARY
          echo "### Outputs" >> $GITHUB_STEP_SUMMARY
          echo "- **DEPLOYMENT_URL**: ${{ steps.variables.outputs.DEPLOYMENT_URL }}" >> $GITHUB_STEP_SUMMARY

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [setup]
    environment:
      name: ${{ inputs.environment }}
      url: ${{ needs.setup.outputs.DEPLOYMENT_URL }}
    env:
      NETLIFY_CLI_VERSION: "21.5.0"
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ inputs.run_id }}
          github-token: ${{ github.token }}
          name: ${{ inputs.artifact_name }}

      - name: Unzip artifact
        run: unzip ${{ inputs.artifact_path }}

      # @see https://cli.netlify.com/commands/deploy/
      - name: Deploy Preview
        if: ${{ inputs.alias != 'master' }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npx netlify-cli@${{ env.NETLIFY_CLI_VERSION }} deploy \
            --alias ${{ inputs.alias }} \
            --dir build \
            --message 'Preview deployment for ${{ inputs.alias }}' \
            --no-build \
            --debug \
            --json

      - name: Deploy Production
        if: ${{ inputs.alias == 'master' }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npx netlify-cli@${{ env.NETLIFY_CLI_VERSION }} deploy \
            --prod \
            --dir build \
            --message 'Production deployment' \
            --no-build \
            --debug \
            --json

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        if: ${{ inputs.pr_number > 0 }}
        with:
          pr-number: ${{ inputs.pr_number }}
          message: |
            Deployed a **preview** version to ${{ needs.setup.outputs.DEPLOYMENT_URL }}
          comment-tag: deployment

      - name: Summary
        if: always()
        run: |
          echo "## Deploy Details" >> $GITHUB_STEP_SUMMARY
          echo "This workflow ran on **$(date)**." >> $GITHUB_STEP_SUMMARY
          echo "### Inputs" >> $GITHUB_STEP_SUMMARY
          echo "- **alias**: \`${{ inputs.alias }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **artifact_name**: \`${{ inputs.artifact_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **artifact_path**: \`${{ inputs.artifact_path }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **run_id**: \`${{ inputs.run_id }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **pr_number**: \`${{ inputs.pr_number }}\`" >> $GITHUB_STEP_SUMMARY
