name: Deploy DEV
run-name: 'Trigger DEV deployment #${{ github.run_number }} triggered by ${{ github.actor }} on ${{ github.ref }}'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - run: echo Hello World
