name: Nexus Tag Associate
run-name: 'Nexus associate tag workflow #${{ github.run_number }} triggered by ${{ github.actor }}'

on:
  workflow_call:
    secrets:
      NEXUS_PW:
        required: true
    inputs:
      name:
        description: 'The tag name to create'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      name:
        description: 'The tag name to create'
        type: string
        required: true

env:
  NEXUS3_URL: ${{ vars.NEXUS3_URL }}
  NEXUS3_USER: ${{ vars.NEXUS3_USER }}

jobs:
  associate:
    name: Tag Associate
    runs-on: ubuntu-latest
    steps:
      # https://help.sonatype.com/en/tagging.html
      - name: Associate Components with Nexus Tag
        run: |
          echo hello
