name: Preview Build

on:
  push:
    branches-ignore:
      - master
      - dependabot/**

# Prevent running builds for the same branch in parallel
# New workflows will cancel existing workflows…
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (preview)
    uses: ./.github/workflows/build.yml
    secrets:
      NEXUS3_PW: ${{ secrets.NEXUS3_PW }}
      NEXUS_NPM_TOKEN_READ_ONLY: ${{ secrets.NEXUS_NPM_TOKEN_READ_ONLY }}
      MACDUFF_KEYCHAIN_PASSWORD: ${{ secrets.MACDUFF_KEYCHAIN_PASSWORD }}

  tag:
    name: Nexus Tagging
    needs: [build]
    uses: uniport/workflows/.github/workflows/tag-nexus-artifacts.yml@main
    with:
      version: ${{ needs.build.outputs.VERSION }}
      group_id: ${{ needs.build.outputs.GROUP_ID }}
      tag_docker: true
      tag_maven: true
    secrets:
      NEXUS3_PW: ${{ secrets.NEXUS3_PW }}

  docs:
    name: Deploy Docs (preview)
    needs: [build]
    uses: ./.github/workflows/deploy-docs.yml
    # Do not deploy on forks
    if: ${{ !github.repository.fork }}
    permissions:
      actions: read
      statuses: write
      pull-requests: write
      deployments: write
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    with:
      alias: ${{ needs.build.outputs.branch_name_slug }}
      artifact_name: ${{ needs.build.outputs.docs_artifact_name }}
      artifact_path: ${{ needs.build.outputs.docs_artifact_path }}
      run_id: ${{ needs.build.outputs.run_id }}
      environment: docs
