name: Feature-Branch Checks

on:
  push:
    branches-ignore:
      - "master"

# Prevent running checks for the same branch in parallel
# New workflows will cancel existing workflows…
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (preview)
    uses: ./.github/workflows/build.yml
    secrets: inherit
