name: Release
run-name: "Release ${{ inputs.version }} on ${{ inputs.target_branch }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version string"
        required: true
        type: string
      target_branch:
        description: "The branch where the changelog will be updated and the version bumped"
        required: true
        type: string
      promote_artifacts:
        description: "Promote Nexus3 artifacts"
        default: true
        type: boolean
      create_tag:
        description: "Create the git tag"
        default: true
        type: boolean
      update_changelog:
        description: "Update the changelog"
        default: true
        type: boolean
      create_patch_branch:
        description: "Create the git patch branch"
        default: true
        type: boolean
      bump_version:
        description: "Set the next version"
        default: true
        type: boolean
      jira_release:
        description: "Do a Jira release"
        default: true
        type: boolean
      update_archetype:
        description: "Update the archetype"
        default: true
        type: boolean
      github_release:
        description: "Create a GitHub release"
        default: true
        type: boolean
      send_announcement:
        description: "Announce the release on Rocket.Chat"
        default: true
        type: boolean

jobs:
  release:
    name: Release
    uses: uniport/workflows/.github/workflows/release.yml@main
    permissions:
      contents: write # create tag, create branch, update version, update changelog
    with:
      version: ${{ inputs.version }}
      target_branch: ${{ inputs.target_branch }}
      promote_artifacts: ${{ inputs.promote_artifacts }}
      create_tag: ${{ inputs.create_tag }}
      update_changelog: ${{ inputs.update_changelog }}
      create_patch_branch: ${{ inputs.create_patch_branch }}
      bump_version: ${{ inputs.bump_version }}
      jira_release: ${{ inputs.jira_release }}
      update_archetype: ${{ inputs.update_archetype }}
      github_release: ${{ inputs.github_release }}
      send_announcement: ${{ inputs.send_announcement }}
      jira_release_name_prefix: ${{ vars.JIRA_RELEASE_NAME_PREFIX }}
      archetype_component_name: ${{ vars.ARCHETYPE_COMPONENT_NAME }}
    secrets:
      NEXUS3_PW: ${{ secrets.NEXUS3_PW }}
      ATLASSIAN_AUTH_TOKEN: ${{ secrets.ATLASSIAN_AUTH_TOKEN }}
      UNIPORT_APP_PRIVATE_KEY: ${{ secrets.UNIPORT_APP_PRIVATE_KEY }}
      ROCKETCHAT_WEBHOOK_URL: ${{ secrets.ROCKETCHAT_WEBHOOK_URL }}
