name: Trigger Release Pipeline
run-name: "Trigger release pipeline workflow #${{ github.run_number }} triggered by ${{ github.actor }} on ${{ github.ref }}"

on:
  workflow_call:
    inputs:
      version:
        description: "The version string"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: "The version string"
        required: true
        type: string

env:
  RELEASE_JOB_URL: "https://ci.inventage.com/job/Inventage%20Portal/job/Portal%20Gateway/job/Release/buildWithParameters"

jobs:
  trigger:
    name: Trigger Release Pipeline
    runs-on: [self-hosted, macOS]
    env:
      WORKFLOW_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Fetch only the latest commit

      - name: Validate version format
        uses: uniport/workflows/.github/actions/validate-version@main
        with:
          version: ${{ inputs.version }}

      - name: Trigger Jenkins Release Pipeline
        run: |
          curl -fSs -X POST \
          -u '${{ vars.NEXUS3_USER }}:${{ secrets.JENKINS_AUTH_TOKEN }}' \
          --url '${{ env.RELEASE_JOB_URL }}' \
          --data GIT_RELEASE_BRANCH_NAME='${{ github.ref_name }}' \
          --data PACKAGE_VERSION='${{ inputs.version }}' \
          --data PROMOTION_TAG_DOCKER='${{ inputs.version }}_docker' \
          --data PROMOTION_TAG_HELM='${{ inputs.version }}_helm' \
          --data PROMOTION_TAG_MVN='${{ inputs.version }}_mvn' \
          --data PROMOTION_TAG_NPM='${{ inputs.version }}_npm' \
          --data UPSTREAM_BUILD_URL='${{ env.WORKFLOW_RUN_URL }}'
