name: Update Archetype
run-name: 'Update archetype #${{ github.run_number }} triggered by ${{ github.actor }}'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to register'
        type: string
        required: true
      command:
        description: 'The command to use in the registerVersion.sh script'
        type: choice
        required: true
        default: 'snapshot'
        options:
          - 'snapshot'
          - 'release'
  workflow_call:
    secrets:
      ARCHETYPE_DEPLOY_KEY:
        required: true
    inputs:
      version:
        description: 'The version to register'
        type: string
        required: true
      command:
        description: 'The command to use in the registerVersion.sh script'
        type: string
        default: 'snapshot'

env:
  UNIPORT_ARCHETYPE_REPOSITORY: uniport/archetype-inventage-portal-solution

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout archetype
        uses: actions/checkout@v4
        with:
          repository: ${{ env.UNIPORT_ARCHETYPE_REPOSITORY }}
          ssh-key: ${{ secrets.ARCHETYPE_DEPLOY_KEY }}
          ref: master

      - name: Configure Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Register version
        run: |
          ./registerVersion.sh ${{ inputs.command }} portal-gateway ${{ inputs.version }}

      - name: Push all changes
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          repository: ${{ env.UNIPORT_ARCHETYPE_REPOSITORY }}
          branch: master
